extends Node

var COLOR_BUTTON_ACTiVE_BKGD = Color.DARK_GREEN
var COLOR_BUTTON_DISABLED_BKGD = Color.DARK_SEA_GREEN

var COLOR_BUTTON_ACTIVE_BORDER = Color.BLACK
var COLOR_BUTTON_DISABLED_BORDER = Color.DIM_GRAY

var COLOR_BUTTON_HIDDEN = Color(1,1,1,0)
