extends Node


var COLOR_SOLVE_BTN_ACTiVE_BKGD = Color.SEA_GREEN
var COLOR_SOLVE_BTN_DISABLED_BKGD = Color.WEB_GRAY

var COLOR_SOLVE_BTN_ACTIVE_BORDER = Color.BLACK
var COLOR_SOLVE_BTN_DISABLED_BORDER = Color.DIM_GRAY

var COLOR_BUTTON_HIDDEN = Color(1,1,1,0)
